version: 0.0
os: windows
files:
  - source: \
    destination: c:\inetpub\wwwroot\BasicApp
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: \before-install.ps1
      timeout: 900
  AfterInstall:
    - location: \after-install.ps1
      timeout: 900